---
- !<tag:supmua.org,2006-10-01/Redwood/Maildir>
  uri: maildir:/home/gg/.mail/migadu/Inbox
  usual: true
  archived: false
  sync_back: true
  id: 1
  labels:
  - inbox
- !<tag:supmua.org,2006-10-01/Redwood/Maildir>
  uri: maildir:/home/gg/.mail/migadu/Sent
  usual: true
  archived: true
  sync_back: true
  id: 3
  labels:
  - sent
- !<tag:supmua.org,2006-10-01/Redwood/Maildir>
  uri: maildir:/home/gg/.mail/migadu/Archive
  usual: true
  archived: true
  sync_back: true
  id: 2
  labels: []
