#!/bin/sh

## Set up the filters here
## eg:
# notmuch tag -new +newsletters -- from:newsletter
# notmuch tag -new +sent -- tag:new and from:me@example.com


# Everything else goes into the inbox
notmuch tag -new +inbox -- tag:new
