#!/bin/zsh

if [ -z "$SSH_AGENT_PID" ]; then
    eval $(ssh-agent) > /dev/null
fi
if [ "$(uname)" = "Darwin" ]; then
    ssh-add -q --apple-load-keychain
fi

AUTH_FILE=$HOME/.zsh_auth
if [ -e "$AUTH_FILE" ]; then
    . $AUTH_FILE
fi
