#!/bin/sh

output_file=$HOME/.aws/.aws_env_default

account_not_found() {
    echo "Account not found: $1" > /dev/stderr
    exit 1
}

get_account_id() {
    case $1 in
        "IAM")
            echo 721867752048
            ;;

        "Legacy Production")
            echo 755865716437
            ;;

        "Production")
            echo 341175100383
            ;;

        "Staging")
            echo 313303557381
            ;;

        "UAT")
            echo 058180101585
            ;;

        "Ops Production")
            echo 131063299351
            ;;

        "Master")
            echo 587571228087
            ;;

        "Audit")
            echo 895934183267
            ;;

        "Billing")
            echo 101329390560
            ;;

        "CE")
            echo 907024087655
            ;;

        "UK-IT")
            echo 490760426972
            ;;

        "US-IT")
            echo 722917662517
            ;;

        "Ops Dev")
            echo 877470705970
            ;;

        "Originations Dev")
            echo 253851610226
            ;;

        "Data Dev")
            echo 384215217813
            ;;

        "Marketplace Dev")
            echo 355534165012
            ;;

        "Investor Dev")
            echo 400312425723
            ;;

        "Security")
            echo 680225485375
            ;;

        "Infrastructure CI")
            echo 908845046523
            ;;
        *)
            account_not_found "$1"
            ;;
    esac
}

aws_assume_role() {
    okta_aws -u gui.goncalves -r SAML_Engineer -a $(get_account_id $1)
    source $output_file
}
