#!/bin/zsh

. $ZSH_D/aliases
. $ZSH_D/auth
. $ZSH_D/aws_assume_role
. $ZSH_D/completion
. $ZSH_D/fc
. $ZSH_D/pack
. $ZSH_D/prompt

AUTH_FILE=$HOME/.zsh_auth
if [ -n "$AUTH_FILE" ]; then
	. $AUTH_FILE
fi

