#!/bin/zsh

. $ZSH_D/aliases
. $ZSH_D/auth
. $ZSH_D/aws_assume_role
. $ZSH_D/completion
. $ZSH_D/fc
. $ZSH_D/prompt
. $ZSH_D/pack

AUTH_FILE=$HOME/.zsh_auth
if [ -e "$AUTH_FILE" ]; then
	. $AUTH_FILE
fi

