#!/bin/zsh

mesosslave-admin () {
  sft list-servers --project $1 | awk '/mesosslave-admin/{print $1}'
}

alias ssh-uk-uat='ssh "$(mesosslave-admin eu-west-1-uat)"'
alias ssh-uk-stg='ssh "$(mesosslave-admin eu-west-1-staging)"'
alias ssh-uk-prd='ssh "$(mesosslave-admin eu-west-1-production)"'
alias ssh-us-uat='ssh "$(mesosslave-admin us-east-1-uat)"'
alias ssh-us-stg='ssh "$(mesosslave-admin us-east-1-staging)"'
alias ssh-us-prd='ssh "$(mesosslave-admin us-east-1-production)"'

alias rstaging='bin/remote staging || (bin/remote-kill staging && bin/remote staging)'
alias rprod='bin/remote production || (bin/remote-kill production && bin/remote production)'

alias jira="open 'https://jira.fundingcircle.com/secure/RapidBoard.jspa?rapidView=962'"

