#!/bin/zsh

# Load Nix
if [ -e /Users/Gui.Goncalves/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/Gui.Goncalves/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

eval "$(direnv hook zsh)"

export HOMEBREW_NO_ANALYTICS=1
# This is used by ruby-build
export RUBY_CONFIGURE_OPTS="--with-zlib-dir=$(brew --prefix zlib) --with-openssl-dir=$(brew --prefix openssl@1.1)"

export NVM_DIR="$HOME/.nvm"
# [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
# [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export NODE_VERSIONS=$NVM_DIR/versions/node
export NODE_VERSION_PREFIX=v
