#!/bin/zsh

# Load Nix
if [ -e /Users/Gui.Goncalves/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/Gui.Goncalves/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

eval "$(direnv hook zsh)"

export HOMEBREW_NO_ANALYTICS=1

