#!/bin/zsh

. ~/.zsh/vars

alias mv='mv -v'
alias mmv='noglob zmv -W'
alias rm='rm -iv'
alias cp='cp -v'
alias wget='wget --timeout 10'
alias grep='grep --color=auto'
alias c='clear'
alias ll='ls -ahl | more; echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -al | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -al | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"'
alias cdc='cd; clear'
alias ls='ls -GF'
alias ccat='pygmentize -g'

alias mplayer='mplayer -idx'
alias wcat='wget -q -O -'
alias cmake='cmake -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONFDIR=/etc'
alias run='open -a'
alias clearrbc='rm -f */**/*.rbc'
alias dirsizes='du -h -d 1'

alias vim='emacsclient -a "" -t'
alias appini='meld $(find . -name "application.ini") $(find . -name "application.ini.dist")'
alias acl='php $(find . -name acl_deploy.php)'
alias svndiff='svn diff $* | colordiff | lv -c'
alias vgaon='xrandr --output VGA1 --auto --right-of LVDS1'
alias vgaoff='xrandr --output VGA1 --off'
alias ctl='sudo systemctl'
alias halt='sudo poweroff'
alias reboot='sudo reboot'

# Global aliases
alias -g L='| pygmentize -g | less -r'
alias -g BG='& exit'
alias -g C='|wc -l'
alias -g G='|grep'
alias -g H='|head'
alias -g Hl=' --help |& less -r'
alias -g LL='|& less -r'
alias -g N='&>/dev/null'
alias -g V='| vim -'

TF_ALIAS=fuck alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'

alias wurun='docker run -it --rm -v "$(pwd)":/app:Z website-user'
alias wumount='sshfs -o IdentityFile=~/.ssh/id_rsa,auto_cache,reconnect root@manager:/var/www/website_user ~/lastline/manager-website-user'
