#!/usr/bin/env bash

. $BASHRC_D/boilerplate
. $BASHRC_D/prompt
. $BASHRC_D/fortune
. $BASHRC_D/alias
. $BASHRC_D/direnv

if [ $(command -v mise) ]; then
	. $BASHRC_D/mise
fi

. $BASHRC_D/nix
. $BASHRC_D/notes
. $BASHRC_D/doing
. $BASHRC_D/ruby
. $BASHRC_D/scala
. $BASHRC_D/golang
. $BASHRC_D/rust
. $BASHRC_D/bun

if [ $(command -v kitty) ]; then
	. $BASHRC_D/kitty
fi

