#!/usr/bin/env bash

NOTES_FILE=$HOME/sync/life.txt

lf() {
    $EDITOR $NOTES_FILE
}

nt() {
    $PAGER $NOTES_FILE
}

TWTXT_FILE=$HOME/src/gclv.es/static/twtxt.txt
twt() {
    echo -e "`date +%FT%T%:z`\t$*" >> $TWTXT_FILE
}

